name: sentiment
channels:
  - pytorch
  - defaults
dependencies:
  - jupyter=1.0.0
  - numpy=1.19.2
  - pip=20.2.4
  - python=3.8.5
  - pytorch=1.7.0
  - spacy=2.3.2
  - torchtext=0.8.0
  - tqdm=4.50.2
  - pip:
    - gensim==3.8.3
    - matplotlib==3.3.2
    - nltk==3.5
    - pandas==1.1.4
    - scikit-learn==0.23.2
